
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace UNEScrape
{

    public partial class JAreas
    {
        public class Chd3
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Chd")]
            public object Chd;

            [JsonProperty("ID")]
            public int ID;

            [JsonProperty("ID2")]
            public int ID2;

            [JsonProperty("Name")]
            public string Name;

            [JsonProperty("data")]
            public bool Data;
        }
    }

    public partial class JAreas
    {
        public class Chd2
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Chd")]
            public Chd3[] Chd;

            [JsonProperty("ID")]
            public int ID;

            [JsonProperty("ID2")]
            public int ID2;

            [JsonProperty("Name")]
            public string Name;

            [JsonProperty("data")]
            public bool Data;
        }
    }

    public partial class JAreas
    {
        public class D2
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Chd")]
            public Chd2[] Chd;

            [JsonProperty("ID")]
            public int ID;

            [JsonProperty("ID2")]
            public int ID2;

            [JsonProperty("Name")]
            public string Name;

            [JsonProperty("data")]
            public bool Data;
        }
    }

    public partial class JAreas
    {

        [JsonProperty("d")]
        public D2[] D;
    }

}
