
// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace UNEScrape
{

    public partial class JStats
    {
        public class DP
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Dec")]
            public int Dec;

            [JsonProperty("MID")]
            public int MID;

            [JsonProperty("TimeID")]
            public int TimeID;

            [JsonProperty("Value")]
            public Decimal Value;
        }
    }

    public partial class JStats
    {
        public class Datum
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("AreaID")]
            public int AreaID;

            [JsonProperty("DPs")]
            public DP[] DPs;

            [JsonProperty("IndID")]
            public int IndID;

            [JsonProperty("UnitID")]
            public int UnitID;
        }
    }

    public partial class JStats
    {
        public class Time
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Chd")]
            public object Chd;

            [JsonProperty("ID")]
            public int ID;

            [JsonProperty("ID2")]
            public object ID2;

            [JsonProperty("Name")]
            public string Name;

            [JsonProperty("data")]
            public bool Data;
        }
    }

    public partial class JStats
    {
        public class D2
        {

            [JsonProperty("__type")]
            public string Type;

            [JsonProperty("Areas")]
            public object Areas;

            [JsonProperty("Data")]
            public Datum[] Data;

            [JsonProperty("Ind")]
            public object Ind;

            [JsonProperty("Times")]
            public Time[] Times;

            [JsonProperty("Units")]
            public object Units;
        }
    }

    public partial class JStats
    {

        [JsonProperty("d")]
        public D2 D;
    }

}
